import os
import json

import markdown as md
import pandas as pd
import streamlit as st
import plotly.express as px
from dotenv import load_dotenv
from openai import OpenAI
from textwrap import dedent

RISK_COLOURS = {
    "Low": "#6A994E",
    "Medium": "#F2A65A",
    "High": "#C44536"
}

# Functions
# function to create html report
def build_html_report(
    analysis,
    total_projects_count,
    at_risk_count,
    average_delay,
    average_cost_variance_pct,
    correlation,
    project_delays_chart,
    cost_variance_chart,
    scatter_chart
):
    analysis_html = md.markdown(analysis)

    delay_chart_html = project_delays_chart.to_html(
        full_html=False,
        include_plotlyjs="cdn"
    )

    cost_variance_chart_html = cost_variance_chart.to_html(
        full_html=False,
        include_plotlyjs=False
    )

    scatter_chart_html = scatter_chart.to_html(
        full_html=False,
        include_plotlyjs=False
    )

    return dedent(f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Delivery Insights Report (AI Generated)</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                line-height: 1.5;
            }}
            h1, h2, h3 {{
                color: #222;
            }}
            .metric-list {{
                background: #f4f4f4;
                padding: 16px;
                border-radius: 8px;
            }}
            .chart {{
                margin-top: 40px;
                margin-bottom: 40px;
            }}
        </style>
    </head>
    <body>

    <h1>Project Delivery Insights Report</h1>
    <p><em>Generated by AI Project Delivery Insights Assistant</em></p>

    <h2>Portfolio Metrics</h2>
    <div class="metric-list">
    <ul>
        <li>Total projects: {total_projects_count}</li>
        <li>At-risk projects: {at_risk_count}</li>
        <li>Average delay: {average_delay:.1f} days</li>
        <li>Average cost variance: {average_cost_variance_pct:.1f}%</li>
        <li>Delay/cost variance correlation: {correlation:.2f}</li>
    </ul>
    </div>

    <h2>AI Analysis</h2>
    {analysis_html}

    <h2>Charts</h2>

    <div class="chart">
    <h3>Project Delay</h3>
    {delay_chart_html}
    </div>

    <div class="chart">
    <h3>Cost Variance</h3>
    {cost_variance_chart_html}
    </div>

    <div class="chart">
    <h3>Delay vs Cost Variance</h3>
    {scatter_chart_html}
    </div>

    </body>
    </html>
    """
)

# end functions

# begin page load
load_dotenv(override=True)

try:
    api_key = st.secrets["OPENAI_API_KEY"]
except Exception:
    api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(api_key=api_key)

st.set_page_config(
    page_title="AI Project Delivery Insights Assistant",
    layout="wide"
)

st.title("AI Project Delivery Insights Assistant")
st.write(
    """
    This tool helps programme delivery managers quickly identify at-risk projects and understand portfolio delivery performance.
    Upload a CSV of project data to identify at-risk projects, visualise delivery performance,
    and generate an AI-assisted portfolio risk summary.

    The CSV should have the following columns:
    - *Project*: Name of the project
    - *Status*: Current status of the project (Complete, In Progress, Delayed)
    - *Budget*: Original budget for the project (numeric)
    - *ActualCost*: Actual cost incurred to date (numeric)
    - *DelayDays*: Number of days the project is delayed (numeric)
    - *RiskLevel*: Risk level of the project (Low, Medium, High)
   /n
    """
)

uploaded_file = st.file_uploader(
    "Upload a project delivery CSV to begin",
    type=["csv"]
)

required_columns = {
    "Project", "Status", "Budget", "ActualCost", "DelayDays", "RiskLevel"
}



if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    #check for missing columns before processing the file
    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        st.error(f"Missing required columns: {', '.join(missing_columns)}")
        st.stop()

    st.subheader("Data Preview")
    st.dataframe(df)

    df["CostVariance"] = df["ActualCost"] - df["Budget"]
    df["CostVariancePct"] = (df["CostVariance"] / df["Budget"]) * 100

    average_delay = df["DelayDays"].mean()
    at_risk_df = df[
        (df["RiskLevel"] == "High")
        | (df["DelayDays"] > 10)
        | (df["CostVariancePct"] > 10)
    ]

    total_projects_count = len(df)
    at_risk_count = len(at_risk_df)
    average_cost_variance_pct = df["CostVariancePct"].mean()
    correlation = df["DelayDays"].corr(df["CostVariancePct"])

    st.subheader("Portfolio Metrics")

    col1, col2, col3, col4, col5 = st.columns(5)

    col1.metric("Total projects", total_projects_count)
    col2.metric("At risk projects", at_risk_count)
    col3.metric("Average delay (days)", f"{average_delay:.1f}")
    col4.metric("Average cost variance", f"{average_cost_variance_pct:.1f}%")
    col5.metric("Delay / cost correlation", f"{correlation:.2f}")
   

    st.header("Portfolio Risk Analysis")

    # Show definitions of risk levels
    st.info(
        """
        **At-risk definition:** a project is considered at risk if it meets **any** of these criteria:

        - `Risk Level` is `High`
        - `Delay Days` is greater than `10`
        - `Cost Variance Pct` is greater than `10%`
        """
    )

    # Project Delays Chart (only showing projects with >10 days delay for clarity)
    df_sorted_by_delays = df[df["DelayDays"] > 10].sort_values(
        by="DelayDays",
        ascending=False
    )

    st.subheader("Delivery Performance")
    
    project_delays_chart = px.bar(
        df_sorted_by_delays,
        x="Project",
        y="DelayDays",
        color="RiskLevel",
        title="Project Delay (Days) by Risk Level (Only Projects > 10 Days Delay)",
        category_orders={"Project": df_sorted_by_delays["Project"].tolist()},
        color_discrete_map=RISK_COLOURS,
        hover_data={
            "Budget": ":,.0f",
            "ActualCost": ":,.0f",
            "CostVariancePct": True
        }
    )

    st.plotly_chart(
        project_delays_chart, 
        width='stretch'
    )

    # Cost Variance Chart
    df_sorted_by_cost_variance = df.sort_values(
        by="CostVariancePct",
        ascending=False
    )

    cost_variance_chart = px.bar(
        df_sorted_by_cost_variance,
        x="Project",
        y="CostVariancePct",
        color="RiskLevel",
        title="Project Cost Variance (%) by Risk Level",
        category_orders={"Project": df_sorted_by_cost_variance["Project"].tolist()},
        color_discrete_map=RISK_COLOURS,
        hover_data={
            "Budget": ":,.0f",
            "ActualCost": ":,.0f",
            "DelayDays": True
        }
    )

    st.plotly_chart(
        cost_variance_chart, 
        width='stretch'
    )

    # Delay vs Cost Variance Scatter Plot
    scatter_chart = px.scatter(
        df,
        x="DelayDays",
        y="CostVariancePct",
        color="RiskLevel",
        size="ActualCost",
        size_max=30,
        hover_name="Project",
        title="Project Delay vs Cost Variance",
        color_discrete_map=RISK_COLOURS,
        category_orders={
            "RiskLevel": ["High", "Medium", "Low"]
        },
        hover_data={
            "Budget": ":,.0f",
            "ActualCost": ":,.0f",
            "Status": True
        }
    )

    scatter_chart.update_layout(
        xaxis_title="Delay (Days)",
        yaxis_title="Cost Variance (%)"
    )

    scatter_chart.add_hline(
        y=0,
        line_dash="dash",
        line_color="gray"
    )

    scatter_chart.add_vline(
        x=0,
        line_dash="dash",
        line_color="gray"
    )    

    st.plotly_chart(
        scatter_chart,
        width='stretch'
    )

    at_risk_records = at_risk_df.to_dict(orient="records")

    st.subheader("At-Risk projects download")
    st.write("You can download the list of at-risk projects as a CSV file for further analysis or reporting.")

    st.download_button(
        label="Download at-risk projects",
        data=at_risk_df.to_csv(index=False),
        file_name="at_risk_projects.csv",
        mime="text/csv"
    )

    st.header("AI Project Portfolio Analysis")

    analysis_prompt = f"""
        You are a senior programme delivery consultant.

        Portfolio metrics:

        - At-risk projects: {at_risk_count}
        - Average delay: {average_delay:.1f} days
        - Average cost variance: {average_cost_variance_pct:.1f}%
        - Delay/cost variance correlation: {correlation:.2f}

        High risk project records:

        {json.dumps(at_risk_records, indent=2)}

        Return your response in markdown with these sections:

        ## Executive Summary

        ## Observations
        Clearly distinguish observed facts from inferred risks.

        ## Key Risks
        Include reasonable interpretations, but clearly distinguish them from observed facts.

        ## Recommended Actions
        Provide practical delivery management actions.

        Keep the tone concise and professional.
        Only reference issues directly supported by the dataset.
        """

    if st.button("Generate AI Analysis"):
        try:
            with st.spinner("Generating analysis..."):

                response = client.chat.completions.create(
                    model="gpt-4.1-mini",
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are a senior programme delivery consultant "
                                "specialising in software delivery risk."
                            )
                        },
                        {
                            "role": "user",
                            "content": analysis_prompt
                        }
                    ]
                )

                analysis = response.choices[0].message.content

        except Exception as e:
            st.error(f"AI analysis failed: {e}")
            st.stop()

        st.subheader("AI Analysis")
        st.markdown(analysis)

        html_report = build_html_report(
            analysis,
            total_projects_count,
            at_risk_count,
            average_delay,
            average_cost_variance_pct,
            correlation,
            project_delays_chart,
            cost_variance_chart,
            scatter_chart
        )

        st.download_button(
            label="Download Report",
            data=html_report,
            file_name="ai_delivery_insights_report.html",
            mime="text/html"
        )
else:
    st.info("Upload a CSV file to begin.")